name: Docs
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: node --version
    - run: npm --version

    - name: Install
      run: npm install

    - name: Gen Docs
      run: npm run docs

    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: thedudefromci@gmail.com
        branch: gh-pages
        build_dir: docs
        jekyll: no
        commit_message: Updated docs.
